INSERT INTO categoria (nome_categoria) VALUES
('Alimentação'),
('Transporte'),
('Educação'),
('Lazer'),
('Saúde'),
('Moradia'),
('Serviços'),
('Investimentos'),
('Impostos'),
('Compras Online'),
('Assinaturas'),
('Cuidados Pessoais'),
('Viagens'),
('Animais de Estimação'),
('Doações'),
('Reformas'),
('Tecnologia'),
('Roupas'),
('Consultoria'),
('Serviços Domésticos'),
('Pagamentos Diversos'),
('Receitas Eventuais'),
('Rendimentos Financeiros'),
('Serviços Profissionais'),
('Manutenção Veicular');
